services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev  --db postgres --db-url-host keycloak_db --db-username ${KEYCLOAK_DB_USER} --db-password ${KEYCLOAK_DB_PASSWORD}

  keycloak_db:
    image: postgres:17.0
    environment:
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data/pgdata

volumes:
  keycloak_db_data:
